/**
 * `pnpm build:code` — tokenizes each module's code snippets at BUILD time and emits
 * a committed `snippets.gen.ts` beside them.
 *
 * ADR-8 says zero highlighter bytes ship. A Vite `?code` transform would satisfy the
 * app but not `lint:content` or the tests, which import module content directly
 * through tsx. Emitting a plain committed TypeScript file satisfies all three, and
 * makes the token stream reviewable in a diff.
 *
 * Cloze blanks are resolved here, so an ambiguous blank FAILS THE BUILD rather than
 * silently grading the wrong token.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { tokenize, resolveBlanks, lineDiff, type BlankSpec } from '../vite/shiki-plugin'
import { CURRICULUM } from '../content/_curriculum'

export interface SnippetSpec {
  id: string
  file: string
  lang?: string
  label?: string
  blanks?: BlankSpec[]
  /** For code-diff: the sibling file to compare against. */
  diffAgainst?: string
}

let wrote = 0
for (const m of CURRICULUM) {
  const dir = join('content', m.domain, m.id, 'snippets')
  const manifest = join(dir, 'manifest.ts')
  if (!existsSync(manifest)) continue

  const specs = (await import(join(process.cwd(), manifest))).default as SnippetSpec[]
  const blocks: unknown[] = []
  const palettes: Record<string, { light: string; dark: string }> = {}
  const blanks: unknown[] = []
  const changed: Record<string, number[]> = {}

  for (const spec of specs) {
    const path = join(dir, spec.file)
    const src = readFileSync(path, 'utf8')
    const lang = spec.lang ?? spec.file.split('.').pop() ?? 'ts'
    const { lines, palette } = await tokenize(src, lang)
    Object.assign(palettes, palette)
    blocks.push({ id: spec.id, label: spec.label, lines })

    if (spec.blanks?.length) {
      blanks.push(...resolveBlanks({ id: spec.id, lines }, spec.blanks, path))
    }
    if (spec.diffAgainst) {
      const other = readFileSync(join(dir, spec.diffAgainst), 'utf8')
      const d = lineDiff(src.split('\n'), other.split('\n'))
      changed[spec.id] = d.changedA
    }
  }

  const out = `// GENERATED by \`pnpm build:code\`. Do not edit.
// Tokenized at build time (ADR-8): zero highlighter bytes reach the browser.
import type { CodeStageState } from '../../../types'

export const palette = ${JSON.stringify(palettes, null, 1)} as const

export const blocks: CodeStageState['blocks'] = ${JSON.stringify(blocks)}

export const blanks = ${JSON.stringify(blanks)} as { id: string; blockId: string; line: number; token: number; expected: string }[]

export const changed = ${JSON.stringify(changed)} as Record<string, number[]>
`
  writeFileSync(join(dir, 'snippets.gen.ts'), out)
  wrote++
  console.log(`  ${m.id}: ${blocks.length} block(s), ${blanks.length} blank(s), ${Object.keys(palettes).length} palette entries`)
}

console.log(wrote ? `\nwrote ${wrote} snippets.gen.ts` : 'no module has a snippets/manifest.ts yet')
